import { defineMeta } from "blume";

export default defineMeta({
  title: "Blocks",
  icon: "blocks",
  order: 5,
  pages: [
    "index",
    "section",
    "header",
    "divider",
    "context",
    "actions",
    "input",
    "image",
    "rich-text",
    "markdown",
    "table",
    "video",
    "file",
    "context-actions",
    "card",
    "carousel",
    "container",
    "alert",
    "callout",
    "contact-card",
    "data-table",
    "data-visualization",
    "plan",
    "task-card",
    "condition",
  ],
});
