#!/usr/bin/env bun
/**
 * Generates packages/block-kit/src/emoji/data.generated.ts from the `emoji-datasource`
 * devDependency: a name -> unified codepoint map (every short_name, so aliases like `+1` and
 * `thumbsup` both resolve) plus a skin-tone variant map for the emoji that have one.
 *
 * Run with `bun tools/emoji-data/generate.ts` whenever `emoji-datasource` is upgraded.
 */
import { writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";

interface SourceEmoji {
  unified: string;
  short_names: string[];
  skin_variations?: Record<string, { unified: string }>;
}

const ROOT = resolve(import.meta.dir, "../..");
const dataPath = join(ROOT, "node_modules/emoji-datasource/emoji.json");
const outPath = join(ROOT, "packages/block-kit/src/emoji/data.generated.ts");

// The 5 Fitzpatrick modifiers, in Slack's skin-tone-2..6 order (2 = lightest).
const TONE_UNIFIED = ["1F3FB", "1F3FC", "1F3FD", "1F3FE", "1F3FF"];

const source: SourceEmoji[] = JSON.parse(await Bun.file(dataPath).text());

const names: Record<string, string> = {};
const tones: Record<string, string[]> = {};

for (const emoji of source) {
  const unified = emoji.unified.toLowerCase();
  for (const name of emoji.short_names) names[name] = unified;

  if (emoji.skin_variations) {
    const variants = TONE_UNIFIED.map(
      (key) => emoji.skin_variations?.[key]?.unified.toLowerCase() ?? "",
    );
    if (variants.some(Boolean)) tones[unified] = variants;
  }
}

const banner = `/**
 * Generated by tools/emoji-data/generate.ts from emoji-datasource@${
   (
     JSON.parse(await Bun.file(join(dirname(dataPath), "package.json")).text()) as {
       version: string;
     }
   ).version
 }. Do not edit by hand.
 */
`;

const body =
  `${banner}\n` +
  `/** short_name (incl. aliases like "+1") -> lowercase unified codepoint hex, e.g. "1f44d". */\n` +
  `export const EMOJI_NAMES: Record<string, string> = ${JSON.stringify(names)};\n\n` +
  `/** Base unified codepoint -> unified codepoint for skin tones 2-6, "" when that tone has no image. */\n` +
  `export const EMOJI_SKIN_TONES: Record<string, string[]> = ${JSON.stringify(tones)};\n`;

// Format like the rest of the repo so regenerating from the same data is a no-op diff.
const fmt = Bun.spawnSync(["bunx", "oxfmt", "--stdin-filepath", "data.ts"], {
  cwd: ROOT,
  stdin: new TextEncoder().encode(body),
});
if (fmt.exitCode !== 0) throw new Error(`oxfmt failed: ${fmt.stderr.toString()}`);
await writeFile(outPath, fmt.stdout);
console.log(
  `Wrote ${outPath} (${Object.keys(names).length} names, ${Object.keys(tones).length} with skin tones)`,
);
