/*
 * The time zone names Slack's Block Kit Builder shows under a timepicker or datetimepicker
 * ("Time zone: …"), per IANA zone, as measured in the Builder in October 2026: all 422 zones
 * the browser lists plus common aliases. Slack names a zone after a Windows-style region that
 * isn't always the obvious one (Europe/Madrid reads "Amsterdam, Berlin, …", UTC "Monrovia,
 * Reykjavik"), so these are recorded rather than derived. Two Builder glitches are
 * cleaned up rather than copied: it HTML-escapes Tonga's apostrophe ("Nuku&#39;alofa") and names
 * America/Fort_Nelson "(UTC+01:00) Amsterdam, …"; Fort Nelson reads like Dawson Creek, the other
 * UTC-7 zone without daylight saving.
 */

/** The distinct names, referenced by index below. */
const NAMES = [
  "Abu Dhabi, Muscat",
  "Adelaide",
  "Alaska",
  "Aleutian Islands",
  "Amman",
  "Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
  "Anadyr, Petropavlovsk-Kamchatsky",
  "Araguaina",
  "Arizona, Vancouver",
  "Astana",
  "Astrakhan, Ulyanovsk, Volgograd",
  "Asuncion",
  "Athens, Bucharest",
  "Atlantic Time (Canada)",
  "Auckland, Wellington",
  "Azores",
  "Baghdad",
  "Baja California",
  "Baku",
  "Bangkok, Hanoi, Jakarta",
  "Barnaul, Gorno-Altaysk",
  "Beijing, Chongqing, Hong Kong SAR, Urumqi",
  "Beirut",
  "Belgrade, Bratislava, Budapest, Ljubljana, Prague",
  "Bogota, Lima, Quito",
  "Bougainville Island",
  "Brasilia",
  "Brisbane",
  "Brussels, Copenhagen, Madrid, Paris",
  "Cabo Verde Islands",
  "Cairo",
  "Canberra, Melbourne, Sydney",
  "Caracas",
  "Casablanca",
  "Cayenne, Fortaleza",
  "Central America",
  "Central Time (US and Canada)",
  "Chatham Islands",
  "Chennai, Kolkata, Mumbai, New Delhi",
  "Chetumal",
  "Chihuahua",
  "Chita",
  "Chokurdakh",
  "City of Buenos Aires",
  "Cuiaba",
  "Damascus",
  "Darwin",
  "Dhaka",
  "Dublin, Edinburgh, Lisbon, London",
  "Easter Island",
  "Eastern Time (US and Canada)",
  "Ekaterinburg",
  "Eucla",
  "Fernando de Noronha",
  "Fiji Islands",
  "Gaza, Hebron",
  "Georgetown, La Paz, Manaus, San Juan",
  "Greenland",
  "Guadalajara, Mexico City, Monterrey",
  "Guam, Port Moresby",
  "Haiti",
  "Harare, Pretoria",
  "Havana",
  "Hawaii",
  "Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius",
  "Hobart",
  "Hovd",
  "Indiana (East)",
  "Irkutsk",
  "Islamabad, Karachi",
  "Istanbul",
  "Izhevsk, Samara",
  "Jerusalem",
  "Kabul",
  "Kaliningrad",
  "Kathmandu",
  "Kiritimati Island",
  "Krasnoyarsk",
  "Kuala Lumpur, Singapore",
  "Kuwait, Riyadh",
  "La Paz, Mazatlan",
  "Lord Howe Island",
  "Magadan",
  "Marquesas Islands",
  "Midway Island, American Samoa",
  "Minsk",
  "Monrovia, Reykjavik",
  "Montevideo",
  "Moscow, St. Petersburg",
  "Mountain Time (US and Canada), Navajo Nation",
  "Nairobi",
  "Newfoundland",
  "Norfolk Island",
  "Novosibirsk",
  "Nuku'alofa",
  "Osaka, Sapporo, Tokyo",
  "Pacific Time (US and Canada)",
  "Perth",
  "Port Louis",
  "Pyongyang",
  "Saint Pierre and Miquelon",
  "Sakhalin",
  "Salvador",
  "Samoa",
  "Santiago",
  "Sarajevo, Skopje, Warsaw, Zagreb",
  "Saskatchewan",
  "Seoul",
  "Solomon Islands, New Caledonia",
  "Sri Jayawardenepura",
  "Taipei",
  "Tashkent, Ashgabat",
  "Tbilisi",
  "Tehran",
  "Tomsk",
  "Tripoli",
  "Turks and Caicos",
  "Ulaanbaatar",
  "Vladivostok",
  "West Central Africa",
  "Windhoek",
  "Yakutsk",
  "Yangon (Rangoon)",
  "Yerevan",
];

/** IANA zone → index into NAMES. */
const ZONES: Record<string, number> = {
  "Africa/Abidjan": 86,
  "Africa/Accra": 86,
  "Africa/Addis_Ababa": 88,
  "Africa/Algiers": 119,
  "Africa/Asmara": 88,
  "Africa/Asmera": 88,
  "Africa/Bamako": 86,
  "Africa/Bangui": 119,
  "Africa/Banjul": 86,
  "Africa/Bissau": 86,
  "Africa/Blantyre": 61,
  "Africa/Brazzaville": 119,
  "Africa/Bujumbura": 61,
  "Africa/Cairo": 30,
  "Africa/Casablanca": 33,
  "Africa/Ceuta": 5,
  "Africa/Conakry": 86,
  "Africa/Dakar": 86,
  "Africa/Dar_es_Salaam": 88,
  "Africa/Djibouti": 88,
  "Africa/Douala": 119,
  "Africa/El_Aaiun": 33,
  "Africa/Freetown": 86,
  "Africa/Gaborone": 61,
  "Africa/Harare": 61,
  "Africa/Johannesburg": 61,
  "Africa/Juba": 88,
  "Africa/Kampala": 88,
  "Africa/Khartoum": 88,
  "Africa/Kigali": 61,
  "Africa/Kinshasa": 119,
  "Africa/Lagos": 119,
  "Africa/Libreville": 119,
  "Africa/Lome": 86,
  "Africa/Luanda": 119,
  "Africa/Lubumbashi": 61,
  "Africa/Lusaka": 61,
  "Africa/Malabo": 119,
  "Africa/Maputo": 61,
  "Africa/Maseru": 61,
  "Africa/Mbabane": 61,
  "Africa/Mogadishu": 88,
  "Africa/Monrovia": 86,
  "Africa/Nairobi": 90,
  "Africa/Ndjamena": 119,
  "Africa/Niamey": 119,
  "Africa/Nouakchott": 86,
  "Africa/Ouagadougou": 86,
  "Africa/Porto-Novo": 119,
  "Africa/Sao_Tome": 86,
  "Africa/Tripoli": 115,
  "Africa/Tunis": 119,
  "Africa/Windhoek": 120,
  "America/Adak": 3,
  "America/Anchorage": 2,
  "America/Anguilla": 56,
  "America/Antigua": 56,
  "America/Araguaina": 43,
  "America/Argentina/Buenos_Aires": 43,
  "America/Argentina/Catamarca": 43,
  "America/Argentina/Cordoba": 43,
  "America/Argentina/Jujuy": 43,
  "America/Argentina/La_Rioja": 43,
  "America/Argentina/Mendoza": 43,
  "America/Argentina/Rio_Gallegos": 43,
  "America/Argentina/Salta": 43,
  "America/Argentina/San_Juan": 43,
  "America/Argentina/San_Luis": 43,
  "America/Argentina/Tucuman": 43,
  "America/Argentina/Ushuaia": 43,
  "America/Aruba": 56,
  "America/Asuncion": 11,
  "America/Atikokan": 24,
  "America/Bahia": 102,
  "America/Bahia_Banderas": 58,
  "America/Barbados": 56,
  "America/Belem": 43,
  "America/Belize": 35,
  "America/Blanc-Sablon": 56,
  "America/Boa_Vista": 56,
  "America/Bogota": 24,
  "America/Boise": 89,
  "America/Buenos_Aires": 43,
  "America/Cambridge_Bay": 89,
  "America/Campo_Grande": 44,
  "America/Cancun": 39,
  "America/Caracas": 32,
  "America/Catamarca": 43,
  "America/Cayenne": 34,
  "America/Cayman": 24,
  "America/Chicago": 36,
  "America/Chihuahua": 40,
  "America/Coral_Harbour": 24,
  "America/Cordoba": 43,
  "America/Costa_Rica": 106,
  "America/Creston": 8,
  "America/Cuiaba": 44,
  "America/Curacao": 56,
  "America/Danmarkshavn": 86,
  "America/Dawson": 96,
  "America/Dawson_Creek": 8,
  "America/Denver": 89,
  "America/Detroit": 50,
  "America/Dominica": 56,
  "America/Edmonton": 89,
  "America/Eirunepe": 24,
  "America/El_Salvador": 106,
  "America/Fort_Nelson": 8,
  "America/Fortaleza": 7,
  "America/Glace_Bay": 13,
  "America/Godthab": 57,
  "America/Goose_Bay": 13,
  "America/Grand_Turk": 116,
  "America/Grenada": 56,
  "America/Guadeloupe": 56,
  "America/Guatemala": 106,
  "America/Guayaquil": 24,
  "America/Guyana": 56,
  "America/Halifax": 13,
  "America/Havana": 62,
  "America/Hermosillo": 8,
  "America/Indiana/Indianapolis": 67,
  "America/Indiana/Knox": 36,
  "America/Indiana/Marengo": 50,
  "America/Indiana/Petersburg": 50,
  "America/Indiana/Tell_City": 36,
  "America/Indiana/Vevay": 50,
  "America/Indiana/Vincennes": 50,
  "America/Indiana/Winamac": 50,
  "America/Indianapolis": 50,
  "America/Inuvik": 89,
  "America/Iqaluit": 50,
  "America/Jamaica": 24,
  "America/Jujuy": 43,
  "America/Juneau": 2,
  "America/Kentucky/Louisville": 50,
  "America/Kentucky/Monticello": 50,
  "America/Kralendijk": 56,
  "America/La_Paz": 56,
  "America/Lima": 24,
  "America/Los_Angeles": 96,
  "America/Louisville": 50,
  "America/Lower_Princes": 56,
  "America/Maceio": 43,
  "America/Managua": 106,
  "America/Manaus": 56,
  "America/Marigot": 56,
  "America/Martinique": 56,
  "America/Matamoros": 36,
  "America/Mazatlan": 80,
  "America/Mendoza": 43,
  "America/Menominee": 36,
  "America/Merida": 58,
  "America/Mexico_City": 58,
  "America/Miquelon": 100,
  "America/Moncton": 13,
  "America/Monterrey": 58,
  "America/Montevideo": 87,
  "America/Montreal": 50,
  "America/Montserrat": 56,
  "America/Nassau": 50,
  "America/New_York": 50,
  "America/Nome": 2,
  "America/Noronha": 53,
  "America/North_Dakota/Beulah": 36,
  "America/North_Dakota/Center": 36,
  "America/North_Dakota/New_Salem": 36,
  "America/Ojinaga": 36,
  "America/Panama": 24,
  "America/Paramaribo": 43,
  "America/Phoenix": 8,
  "America/Port-au-Prince": 60,
  "America/Port_of_Spain": 56,
  "America/Porto_Velho": 56,
  "America/Puerto_Rico": 56,
  "America/Rankin_Inlet": 36,
  "America/Recife": 43,
  "America/Regina": 106,
  "America/Resolute": 36,
  "America/Rio_Branco": 24,
  "America/Santarem": 43,
  "America/Santiago": 104,
  "America/Santo_Domingo": 56,
  "America/Sao_Paulo": 26,
  "America/Scoresbysund": 15,
  "America/Sitka": 2,
  "America/St_Barthelemy": 56,
  "America/St_Johns": 91,
  "America/St_Kitts": 56,
  "America/St_Lucia": 56,
  "America/St_Thomas": 56,
  "America/St_Vincent": 56,
  "America/Swift_Current": 106,
  "America/Tegucigalpa": 106,
  "America/Thule": 13,
  "America/Tijuana": 17,
  "America/Toronto": 50,
  "America/Tortola": 56,
  "America/Vancouver": 8,
  "America/Whitehorse": 96,
  "America/Winnipeg": 36,
  "America/Yakutat": 2,
  "Antarctica/Casey": 21,
  "Antarctica/Davis": 19,
  "Antarctica/DumontDUrville": 27,
  "Antarctica/Macquarie": 25,
  "Antarctica/Mawson": 111,
  "Antarctica/McMurdo": 14,
  "Antarctica/Palmer": 104,
  "Antarctica/Rothera": 43,
  "Antarctica/Syowa": 88,
  "Antarctica/Vostok": 47,
  "Arctic/Longyearbyen": 5,
  "Asia/Aden": 88,
  "Asia/Almaty": 9,
  "Asia/Amman": 4,
  "Asia/Anadyr": 6,
  "Asia/Aqtau": 111,
  "Asia/Aqtobe": 111,
  "Asia/Ashgabat": 111,
  "Asia/Baghdad": 16,
  "Asia/Bahrain": 88,
  "Asia/Baku": 18,
  "Asia/Bangkok": 19,
  "Asia/Barnaul": 20,
  "Asia/Beirut": 22,
  "Asia/Bishkek": 47,
  "Asia/Brunei": 21,
  "Asia/Calcutta": 38,
  "Asia/Chita": 41,
  "Asia/Chongqing": 21,
  "Asia/Colombo": 109,
  "Asia/Damascus": 45,
  "Asia/Dhaka": 47,
  "Asia/Dili": 95,
  "Asia/Dubai": 0,
  "Asia/Dushanbe": 111,
  "Asia/Gaza": 55,
  "Asia/Hebron": 55,
  "Asia/Ho_Chi_Minh": 19,
  "Asia/Hong_Kong": 21,
  "Asia/Hovd": 66,
  "Asia/Irkutsk": 68,
  "Asia/Istanbul": 70,
  "Asia/Jakarta": 19,
  "Asia/Jayapura": 95,
  "Asia/Jerusalem": 72,
  "Asia/Kabul": 73,
  "Asia/Kamchatka": 6,
  "Asia/Karachi": 69,
  "Asia/Kashgar": 47,
  "Asia/Kathmandu": 75,
  "Asia/Katmandu": 75,
  "Asia/Khandyga": 95,
  "Asia/Kolkata": 38,
  "Asia/Krasnoyarsk": 77,
  "Asia/Kuala_Lumpur": 78,
  "Asia/Kuching": 21,
  "Asia/Kuwait": 79,
  "Asia/Macau": 21,
  "Asia/Magadan": 82,
  "Asia/Makassar": 21,
  "Asia/Manila": 21,
  "Asia/Muscat": 0,
  "Asia/Nicosia": 12,
  "Asia/Novokuznetsk": 19,
  "Asia/Novosibirsk": 93,
  "Asia/Omsk": 47,
  "Asia/Oral": 111,
  "Asia/Phnom_Penh": 19,
  "Asia/Pontianak": 19,
  "Asia/Pyongyang": 99,
  "Asia/Qatar": 88,
  "Asia/Qyzylorda": 47,
  "Asia/Rangoon": 122,
  "Asia/Riyadh": 88,
  "Asia/Saigon": 19,
  "Asia/Sakhalin": 101,
  "Asia/Samarkand": 111,
  "Asia/Seoul": 107,
  "Asia/Shanghai": 21,
  "Asia/Singapore": 21,
  "Asia/Srednekolymsk": 42,
  "Asia/Taipei": 110,
  "Asia/Tashkent": 111,
  "Asia/Tbilisi": 112,
  "Asia/Tehran": 113,
  "Asia/Thimphu": 47,
  "Asia/Tokyo": 95,
  "Asia/Tomsk": 114,
  "Asia/Ulaanbaatar": 117,
  "Asia/Ulan_Bator": 117,
  "Asia/Urumqi": 47,
  "Asia/Ust-Nera": 27,
  "Asia/Vientiane": 19,
  "Asia/Vladivostok": 118,
  "Asia/Yakutsk": 121,
  "Asia/Yekaterinburg": 51,
  "Asia/Yerevan": 123,
  "Atlantic/Azores": 15,
  "Atlantic/Bermuda": 13,
  "Atlantic/Canary": 48,
  "Atlantic/Cape_Verde": 29,
  "Atlantic/Faeroe": 48,
  "Atlantic/Faroe": 48,
  "Atlantic/Madeira": 48,
  "Atlantic/Reykjavik": 86,
  "Atlantic/South_Georgia": 53,
  "Atlantic/St_Helena": 86,
  "Atlantic/Stanley": 43,
  "Australia/ACT": 31,
  "Australia/Adelaide": 1,
  "Australia/Brisbane": 27,
  "Australia/Broken_Hill": 1,
  "Australia/Darwin": 46,
  "Australia/Eucla": 52,
  "Australia/Hobart": 65,
  "Australia/Lindeman": 27,
  "Australia/Lord_Howe": 81,
  "Australia/Melbourne": 31,
  "Australia/Perth": 97,
  "Australia/Sydney": 31,
  "Etc/GMT": 86,
  "Etc/GMT+5": 24,
  "Etc/UTC": 86,
  "Europe/Amsterdam": 5,
  "Europe/Andorra": 5,
  "Europe/Astrakhan": 10,
  "Europe/Athens": 12,
  "Europe/Belfast": 48,
  "Europe/Belgrade": 23,
  "Europe/Berlin": 5,
  "Europe/Bratislava": 5,
  "Europe/Brussels": 28,
  "Europe/Bucharest": 12,
  "Europe/Budapest": 5,
  "Europe/Busingen": 5,
  "Europe/Copenhagen": 5,
  "Europe/Dublin": 48,
  "Europe/Gibraltar": 5,
  "Europe/Guernsey": 48,
  "Europe/Helsinki": 64,
  "Europe/Isle_of_Man": 48,
  "Europe/Istanbul": 70,
  "Europe/Jersey": 48,
  "Europe/Kaliningrad": 74,
  "Europe/Kirov": 88,
  "Europe/Kyiv": 12,
  "Europe/Lisbon": 48,
  "Europe/Ljubljana": 5,
  "Europe/London": 48,
  "Europe/Luxembourg": 5,
  "Europe/Madrid": 5,
  "Europe/Malta": 5,
  "Europe/Mariehamn": 12,
  "Europe/Minsk": 85,
  "Europe/Monaco": 5,
  "Europe/Moscow": 88,
  "Europe/Oslo": 5,
  "Europe/Paris": 5,
  "Europe/Podgorica": 5,
  "Europe/Prague": 23,
  "Europe/Riga": 12,
  "Europe/Rome": 5,
  "Europe/Samara": 71,
  "Europe/San_Marino": 5,
  "Europe/Sarajevo": 5,
  "Europe/Simferopol": 88,
  "Europe/Skopje": 5,
  "Europe/Sofia": 12,
  "Europe/Stockholm": 5,
  "Europe/Tallinn": 12,
  "Europe/Tirane": 5,
  "Europe/Ulyanovsk": 10,
  "Europe/Vaduz": 5,
  "Europe/Vatican": 5,
  "Europe/Vienna": 5,
  "Europe/Vilnius": 12,
  "Europe/Volgograd": 10,
  "Europe/Warsaw": 105,
  "Europe/Zagreb": 5,
  "Europe/Zurich": 5,
  GMT: 86,
  "Indian/Antananarivo": 88,
  "Indian/Chagos": 47,
  "Indian/Christmas": 19,
  "Indian/Cocos": 122,
  "Indian/Comoro": 88,
  "Indian/Kerguelen": 111,
  "Indian/Mahe": 0,
  "Indian/Maldives": 111,
  "Indian/Mauritius": 98,
  "Indian/Mayotte": 88,
  "Indian/Reunion": 0,
  "Pacific/Apia": 103,
  "Pacific/Auckland": 14,
  "Pacific/Bougainville": 25,
  "Pacific/Chatham": 37,
  "Pacific/Chuuk": 27,
  "Pacific/Easter": 49,
  "Pacific/Efate": 25,
  "Pacific/Enderbury": 94,
  "Pacific/Fakaofo": 94,
  "Pacific/Fiji": 54,
  "Pacific/Funafuti": 6,
  "Pacific/Galapagos": 106,
  "Pacific/Guadalcanal": 108,
  "Pacific/Guam": 59,
  "Pacific/Honolulu": 63,
  "Pacific/Kiritimati": 76,
  "Pacific/Kosrae": 25,
  "Pacific/Kwajalein": 6,
  "Pacific/Majuro": 6,
  "Pacific/Marquesas": 83,
  "Pacific/Midway": 84,
  "Pacific/Nauru": 6,
  "Pacific/Niue": 84,
  "Pacific/Norfolk": 92,
  "Pacific/Noumea": 25,
  "Pacific/Pago_Pago": 84,
  "Pacific/Palau": 95,
  "Pacific/Pohnpei": 25,
  "Pacific/Ponape": 25,
  "Pacific/Port_Moresby": 27,
  "Pacific/Rarotonga": 63,
  "Pacific/Saipan": 27,
  "Pacific/Tahiti": 63,
  "Pacific/Tarawa": 6,
  "Pacific/Tongatapu": 94,
  "Pacific/Truk": 27,
  "Pacific/Wake": 6,
  "Pacific/Wallis": 6,
  "US/Eastern": 50,
  "US/Pacific": 96,
  UTC: 86,
};

/** Slack's name for an IANA zone, if the Builder named it. */
export function slackTimeZoneName(timeZone: string): string | undefined {
  const index = ZONES[timeZone];
  return index === undefined ? undefined : NAMES[index];
}
