/*
 * The time zone names Slack's Block Kit Builder shows under a timepicker or datetimepicker
 * ("Time zone: …"), per IANA zone, as measured in the Builder in October 2026: all 422 zones
 * the browser lists plus common aliases. Slack names a zone after a Windows-style region that
 * isn't always the obvious one (Europe/Madrid reads "Amsterdam, Berlin, …", UTC "Monrovia,
 * Reykjavik"), so these are recorded rather than derived. "Nuku&#39;alofa" is how Slack shows it.
 */

/** The distinct names, referenced by index below. */
const NAMES = [
  "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
  "Abu Dhabi, Muscat",
  "Adelaide",
  "Alaska",
  "Aleutian Islands",
  "Amman",
  "Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
  "Anadyr, Petropavlovsk-Kamchatsky",
  "Araguaina",
  "Arizona, Vancouver",
  "Astana",
  "Astrakhan, Ulyanovsk, Volgograd",
  "Asuncion",
  "Athens, Bucharest",
  "Atlantic Time (Canada)",
  "Auckland, Wellington",
  "Azores",
  "Baghdad",
  "Baja California",
  "Baku",
  "Bangkok, Hanoi, Jakarta",
  "Barnaul, Gorno-Altaysk",
  "Beijing, Chongqing, Hong Kong SAR, Urumqi",
  "Beirut",
  "Belgrade, Bratislava, Budapest, Ljubljana, Prague",
  "Bogota, Lima, Quito",
  "Bougainville Island",
  "Brasilia",
  "Brisbane",
  "Brussels, Copenhagen, Madrid, Paris",
  "Cabo Verde Islands",
  "Cairo",
  "Canberra, Melbourne, Sydney",
  "Caracas",
  "Casablanca",
  "Cayenne, Fortaleza",
  "Central America",
  "Central Time (US and Canada)",
  "Chatham Islands",
  "Chennai, Kolkata, Mumbai, New Delhi",
  "Chetumal",
  "Chihuahua",
  "Chita",
  "Chokurdakh",
  "City of Buenos Aires",
  "Cuiaba",
  "Damascus",
  "Darwin",
  "Dhaka",
  "Dublin, Edinburgh, Lisbon, London",
  "Easter Island",
  "Eastern Time (US and Canada)",
  "Ekaterinburg",
  "Eucla",
  "Fernando de Noronha",
  "Fiji Islands",
  "Gaza, Hebron",
  "Georgetown, La Paz, Manaus, San Juan",
  "Greenland",
  "Guadalajara, Mexico City, Monterrey",
  "Guam, Port Moresby",
  "Haiti",
  "Harare, Pretoria",
  "Havana",
  "Hawaii",
  "Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius",
  "Hobart",
  "Hovd",
  "Indiana (East)",
  "Irkutsk",
  "Islamabad, Karachi",
  "Istanbul",
  "Izhevsk, Samara",
  "Jerusalem",
  "Kabul",
  "Kaliningrad",
  "Kathmandu",
  "Kiritimati Island",
  "Krasnoyarsk",
  "Kuala Lumpur, Singapore",
  "Kuwait, Riyadh",
  "La Paz, Mazatlan",
  "Lord Howe Island",
  "Magadan",
  "Marquesas Islands",
  "Midway Island, American Samoa",
  "Minsk",
  "Monrovia, Reykjavik",
  "Montevideo",
  "Moscow, St. Petersburg",
  "Mountain Time (US and Canada), Navajo Nation",
  "Nairobi",
  "Newfoundland",
  "Norfolk Island",
  "Novosibirsk",
  "Nuku&#39;alofa",
  "Osaka, Sapporo, Tokyo",
  "Pacific Time (US and Canada)",
  "Perth",
  "Port Louis",
  "Pyongyang",
  "Saint Pierre and Miquelon",
  "Sakhalin",
  "Salvador",
  "Samoa",
  "Santiago",
  "Sarajevo, Skopje, Warsaw, Zagreb",
  "Saskatchewan",
  "Seoul",
  "Solomon Islands, New Caledonia",
  "Sri Jayawardenepura",
  "Taipei",
  "Tashkent, Ashgabat",
  "Tbilisi",
  "Tehran",
  "Tomsk",
  "Tripoli",
  "Turks and Caicos",
  "Ulaanbaatar",
  "Vladivostok",
  "West Central Africa",
  "Windhoek",
  "Yakutsk",
  "Yangon (Rangoon)",
  "Yerevan",
];

/** IANA zone → index into NAMES. */
const ZONES: Record<string, number> = {
  "Africa/Abidjan": 87,
  "Africa/Accra": 87,
  "Africa/Addis_Ababa": 89,
  "Africa/Algiers": 120,
  "Africa/Asmara": 89,
  "Africa/Asmera": 89,
  "Africa/Bamako": 87,
  "Africa/Bangui": 120,
  "Africa/Banjul": 87,
  "Africa/Bissau": 87,
  "Africa/Blantyre": 62,
  "Africa/Brazzaville": 120,
  "Africa/Bujumbura": 62,
  "Africa/Cairo": 31,
  "Africa/Casablanca": 34,
  "Africa/Ceuta": 6,
  "Africa/Conakry": 87,
  "Africa/Dakar": 87,
  "Africa/Dar_es_Salaam": 89,
  "Africa/Djibouti": 89,
  "Africa/Douala": 120,
  "Africa/El_Aaiun": 34,
  "Africa/Freetown": 87,
  "Africa/Gaborone": 62,
  "Africa/Harare": 62,
  "Africa/Johannesburg": 62,
  "Africa/Juba": 89,
  "Africa/Kampala": 89,
  "Africa/Khartoum": 89,
  "Africa/Kigali": 62,
  "Africa/Kinshasa": 120,
  "Africa/Lagos": 120,
  "Africa/Libreville": 120,
  "Africa/Lome": 87,
  "Africa/Luanda": 120,
  "Africa/Lubumbashi": 62,
  "Africa/Lusaka": 62,
  "Africa/Malabo": 120,
  "Africa/Maputo": 62,
  "Africa/Maseru": 62,
  "Africa/Mbabane": 62,
  "Africa/Mogadishu": 89,
  "Africa/Monrovia": 87,
  "Africa/Nairobi": 91,
  "Africa/Ndjamena": 120,
  "Africa/Niamey": 120,
  "Africa/Nouakchott": 87,
  "Africa/Ouagadougou": 87,
  "Africa/Porto-Novo": 120,
  "Africa/Sao_Tome": 87,
  "Africa/Tripoli": 116,
  "Africa/Tunis": 120,
  "Africa/Windhoek": 121,
  "America/Adak": 4,
  "America/Anchorage": 3,
  "America/Anguilla": 57,
  "America/Antigua": 57,
  "America/Araguaina": 44,
  "America/Argentina/Buenos_Aires": 44,
  "America/Argentina/Catamarca": 44,
  "America/Argentina/Cordoba": 44,
  "America/Argentina/Jujuy": 44,
  "America/Argentina/La_Rioja": 44,
  "America/Argentina/Mendoza": 44,
  "America/Argentina/Rio_Gallegos": 44,
  "America/Argentina/Salta": 44,
  "America/Argentina/San_Juan": 44,
  "America/Argentina/San_Luis": 44,
  "America/Argentina/Tucuman": 44,
  "America/Argentina/Ushuaia": 44,
  "America/Aruba": 57,
  "America/Asuncion": 12,
  "America/Atikokan": 25,
  "America/Bahia": 103,
  "America/Bahia_Banderas": 59,
  "America/Barbados": 57,
  "America/Belem": 44,
  "America/Belize": 36,
  "America/Blanc-Sablon": 57,
  "America/Boa_Vista": 57,
  "America/Bogota": 25,
  "America/Boise": 90,
  "America/Buenos_Aires": 44,
  "America/Cambridge_Bay": 90,
  "America/Campo_Grande": 45,
  "America/Cancun": 40,
  "America/Caracas": 33,
  "America/Catamarca": 44,
  "America/Cayenne": 35,
  "America/Cayman": 25,
  "America/Chicago": 37,
  "America/Chihuahua": 41,
  "America/Coral_Harbour": 25,
  "America/Cordoba": 44,
  "America/Costa_Rica": 107,
  "America/Creston": 9,
  "America/Cuiaba": 45,
  "America/Curacao": 57,
  "America/Danmarkshavn": 87,
  "America/Dawson": 97,
  "America/Dawson_Creek": 9,
  "America/Denver": 90,
  "America/Detroit": 51,
  "America/Dominica": 57,
  "America/Edmonton": 90,
  "America/Eirunepe": 25,
  "America/El_Salvador": 107,
  "America/Fort_Nelson": 0,
  "America/Fortaleza": 8,
  "America/Glace_Bay": 14,
  "America/Godthab": 58,
  "America/Goose_Bay": 14,
  "America/Grand_Turk": 117,
  "America/Grenada": 57,
  "America/Guadeloupe": 57,
  "America/Guatemala": 107,
  "America/Guayaquil": 25,
  "America/Guyana": 57,
  "America/Halifax": 14,
  "America/Havana": 63,
  "America/Hermosillo": 9,
  "America/Indiana/Indianapolis": 68,
  "America/Indiana/Knox": 37,
  "America/Indiana/Marengo": 51,
  "America/Indiana/Petersburg": 51,
  "America/Indiana/Tell_City": 37,
  "America/Indiana/Vevay": 51,
  "America/Indiana/Vincennes": 51,
  "America/Indiana/Winamac": 51,
  "America/Indianapolis": 51,
  "America/Inuvik": 90,
  "America/Iqaluit": 51,
  "America/Jamaica": 25,
  "America/Jujuy": 44,
  "America/Juneau": 3,
  "America/Kentucky/Louisville": 51,
  "America/Kentucky/Monticello": 51,
  "America/Kralendijk": 57,
  "America/La_Paz": 57,
  "America/Lima": 25,
  "America/Los_Angeles": 97,
  "America/Louisville": 51,
  "America/Lower_Princes": 57,
  "America/Maceio": 44,
  "America/Managua": 107,
  "America/Manaus": 57,
  "America/Marigot": 57,
  "America/Martinique": 57,
  "America/Matamoros": 37,
  "America/Mazatlan": 81,
  "America/Mendoza": 44,
  "America/Menominee": 37,
  "America/Merida": 59,
  "America/Mexico_City": 59,
  "America/Miquelon": 101,
  "America/Moncton": 14,
  "America/Monterrey": 59,
  "America/Montevideo": 88,
  "America/Montreal": 51,
  "America/Montserrat": 57,
  "America/Nassau": 51,
  "America/New_York": 51,
  "America/Nome": 3,
  "America/Noronha": 54,
  "America/North_Dakota/Beulah": 37,
  "America/North_Dakota/Center": 37,
  "America/North_Dakota/New_Salem": 37,
  "America/Ojinaga": 37,
  "America/Panama": 25,
  "America/Paramaribo": 44,
  "America/Phoenix": 9,
  "America/Port-au-Prince": 61,
  "America/Port_of_Spain": 57,
  "America/Porto_Velho": 57,
  "America/Puerto_Rico": 57,
  "America/Rankin_Inlet": 37,
  "America/Recife": 44,
  "America/Regina": 107,
  "America/Resolute": 37,
  "America/Rio_Branco": 25,
  "America/Santarem": 44,
  "America/Santiago": 105,
  "America/Santo_Domingo": 57,
  "America/Sao_Paulo": 27,
  "America/Scoresbysund": 16,
  "America/Sitka": 3,
  "America/St_Barthelemy": 57,
  "America/St_Johns": 92,
  "America/St_Kitts": 57,
  "America/St_Lucia": 57,
  "America/St_Thomas": 57,
  "America/St_Vincent": 57,
  "America/Swift_Current": 107,
  "America/Tegucigalpa": 107,
  "America/Thule": 14,
  "America/Tijuana": 18,
  "America/Toronto": 51,
  "America/Tortola": 57,
  "America/Vancouver": 9,
  "America/Whitehorse": 97,
  "America/Winnipeg": 37,
  "America/Yakutat": 3,
  "Antarctica/Casey": 22,
  "Antarctica/Davis": 20,
  "Antarctica/DumontDUrville": 28,
  "Antarctica/Macquarie": 26,
  "Antarctica/Mawson": 112,
  "Antarctica/McMurdo": 15,
  "Antarctica/Palmer": 105,
  "Antarctica/Rothera": 44,
  "Antarctica/Syowa": 89,
  "Antarctica/Vostok": 48,
  "Arctic/Longyearbyen": 6,
  "Asia/Aden": 89,
  "Asia/Almaty": 10,
  "Asia/Amman": 5,
  "Asia/Anadyr": 7,
  "Asia/Aqtau": 112,
  "Asia/Aqtobe": 112,
  "Asia/Ashgabat": 112,
  "Asia/Baghdad": 17,
  "Asia/Bahrain": 89,
  "Asia/Baku": 19,
  "Asia/Bangkok": 20,
  "Asia/Barnaul": 21,
  "Asia/Beirut": 23,
  "Asia/Bishkek": 48,
  "Asia/Brunei": 22,
  "Asia/Calcutta": 39,
  "Asia/Chita": 42,
  "Asia/Chongqing": 22,
  "Asia/Colombo": 110,
  "Asia/Damascus": 46,
  "Asia/Dhaka": 48,
  "Asia/Dili": 96,
  "Asia/Dubai": 1,
  "Asia/Dushanbe": 112,
  "Asia/Gaza": 56,
  "Asia/Hebron": 56,
  "Asia/Ho_Chi_Minh": 20,
  "Asia/Hong_Kong": 22,
  "Asia/Hovd": 67,
  "Asia/Irkutsk": 69,
  "Asia/Istanbul": 71,
  "Asia/Jakarta": 20,
  "Asia/Jayapura": 96,
  "Asia/Jerusalem": 73,
  "Asia/Kabul": 74,
  "Asia/Kamchatka": 7,
  "Asia/Karachi": 70,
  "Asia/Kashgar": 48,
  "Asia/Kathmandu": 76,
  "Asia/Katmandu": 76,
  "Asia/Khandyga": 96,
  "Asia/Kolkata": 39,
  "Asia/Krasnoyarsk": 78,
  "Asia/Kuala_Lumpur": 79,
  "Asia/Kuching": 22,
  "Asia/Kuwait": 80,
  "Asia/Macau": 22,
  "Asia/Magadan": 83,
  "Asia/Makassar": 22,
  "Asia/Manila": 22,
  "Asia/Muscat": 1,
  "Asia/Nicosia": 13,
  "Asia/Novokuznetsk": 20,
  "Asia/Novosibirsk": 94,
  "Asia/Omsk": 48,
  "Asia/Oral": 112,
  "Asia/Phnom_Penh": 20,
  "Asia/Pontianak": 20,
  "Asia/Pyongyang": 100,
  "Asia/Qatar": 89,
  "Asia/Qyzylorda": 48,
  "Asia/Rangoon": 123,
  "Asia/Riyadh": 89,
  "Asia/Saigon": 20,
  "Asia/Sakhalin": 102,
  "Asia/Samarkand": 112,
  "Asia/Seoul": 108,
  "Asia/Shanghai": 22,
  "Asia/Singapore": 22,
  "Asia/Srednekolymsk": 43,
  "Asia/Taipei": 111,
  "Asia/Tashkent": 112,
  "Asia/Tbilisi": 113,
  "Asia/Tehran": 114,
  "Asia/Thimphu": 48,
  "Asia/Tokyo": 96,
  "Asia/Tomsk": 115,
  "Asia/Ulaanbaatar": 118,
  "Asia/Ulan_Bator": 118,
  "Asia/Urumqi": 48,
  "Asia/Ust-Nera": 28,
  "Asia/Vientiane": 20,
  "Asia/Vladivostok": 119,
  "Asia/Yakutsk": 122,
  "Asia/Yekaterinburg": 52,
  "Asia/Yerevan": 124,
  "Atlantic/Azores": 16,
  "Atlantic/Bermuda": 14,
  "Atlantic/Canary": 49,
  "Atlantic/Cape_Verde": 30,
  "Atlantic/Faeroe": 49,
  "Atlantic/Faroe": 49,
  "Atlantic/Madeira": 49,
  "Atlantic/Reykjavik": 87,
  "Atlantic/South_Georgia": 54,
  "Atlantic/St_Helena": 87,
  "Atlantic/Stanley": 44,
  "Australia/ACT": 32,
  "Australia/Adelaide": 2,
  "Australia/Brisbane": 28,
  "Australia/Broken_Hill": 2,
  "Australia/Darwin": 47,
  "Australia/Eucla": 53,
  "Australia/Hobart": 66,
  "Australia/Lindeman": 28,
  "Australia/Lord_Howe": 82,
  "Australia/Melbourne": 32,
  "Australia/Perth": 98,
  "Australia/Sydney": 32,
  "Etc/GMT": 87,
  "Etc/GMT+5": 25,
  "Etc/UTC": 87,
  "Europe/Amsterdam": 6,
  "Europe/Andorra": 6,
  "Europe/Astrakhan": 11,
  "Europe/Athens": 13,
  "Europe/Belfast": 49,
  "Europe/Belgrade": 24,
  "Europe/Berlin": 6,
  "Europe/Bratislava": 6,
  "Europe/Brussels": 29,
  "Europe/Bucharest": 13,
  "Europe/Budapest": 6,
  "Europe/Busingen": 6,
  "Europe/Copenhagen": 6,
  "Europe/Dublin": 49,
  "Europe/Gibraltar": 6,
  "Europe/Guernsey": 49,
  "Europe/Helsinki": 65,
  "Europe/Isle_of_Man": 49,
  "Europe/Istanbul": 71,
  "Europe/Jersey": 49,
  "Europe/Kaliningrad": 75,
  "Europe/Kirov": 89,
  "Europe/Kyiv": 13,
  "Europe/Lisbon": 49,
  "Europe/Ljubljana": 6,
  "Europe/London": 49,
  "Europe/Luxembourg": 6,
  "Europe/Madrid": 6,
  "Europe/Malta": 6,
  "Europe/Mariehamn": 13,
  "Europe/Minsk": 86,
  "Europe/Monaco": 6,
  "Europe/Moscow": 89,
  "Europe/Oslo": 6,
  "Europe/Paris": 6,
  "Europe/Podgorica": 6,
  "Europe/Prague": 24,
  "Europe/Riga": 13,
  "Europe/Rome": 6,
  "Europe/Samara": 72,
  "Europe/San_Marino": 6,
  "Europe/Sarajevo": 6,
  "Europe/Simferopol": 89,
  "Europe/Skopje": 6,
  "Europe/Sofia": 13,
  "Europe/Stockholm": 6,
  "Europe/Tallinn": 13,
  "Europe/Tirane": 6,
  "Europe/Ulyanovsk": 11,
  "Europe/Vaduz": 6,
  "Europe/Vatican": 6,
  "Europe/Vienna": 6,
  "Europe/Vilnius": 13,
  "Europe/Volgograd": 11,
  "Europe/Warsaw": 106,
  "Europe/Zagreb": 6,
  "Europe/Zurich": 6,
  GMT: 87,
  "Indian/Antananarivo": 89,
  "Indian/Chagos": 48,
  "Indian/Christmas": 20,
  "Indian/Cocos": 123,
  "Indian/Comoro": 89,
  "Indian/Kerguelen": 112,
  "Indian/Mahe": 1,
  "Indian/Maldives": 112,
  "Indian/Mauritius": 99,
  "Indian/Mayotte": 89,
  "Indian/Reunion": 1,
  "Pacific/Apia": 104,
  "Pacific/Auckland": 15,
  "Pacific/Bougainville": 26,
  "Pacific/Chatham": 38,
  "Pacific/Chuuk": 28,
  "Pacific/Easter": 50,
  "Pacific/Efate": 26,
  "Pacific/Enderbury": 95,
  "Pacific/Fakaofo": 95,
  "Pacific/Fiji": 55,
  "Pacific/Funafuti": 7,
  "Pacific/Galapagos": 107,
  "Pacific/Guadalcanal": 109,
  "Pacific/Guam": 60,
  "Pacific/Honolulu": 64,
  "Pacific/Kiritimati": 77,
  "Pacific/Kosrae": 26,
  "Pacific/Kwajalein": 7,
  "Pacific/Majuro": 7,
  "Pacific/Marquesas": 84,
  "Pacific/Midway": 85,
  "Pacific/Nauru": 7,
  "Pacific/Niue": 85,
  "Pacific/Norfolk": 93,
  "Pacific/Noumea": 26,
  "Pacific/Pago_Pago": 85,
  "Pacific/Palau": 96,
  "Pacific/Pohnpei": 26,
  "Pacific/Ponape": 26,
  "Pacific/Port_Moresby": 28,
  "Pacific/Rarotonga": 64,
  "Pacific/Saipan": 28,
  "Pacific/Tahiti": 64,
  "Pacific/Tarawa": 7,
  "Pacific/Tongatapu": 95,
  "Pacific/Truk": 28,
  "Pacific/Wake": 7,
  "Pacific/Wallis": 7,
  "US/Eastern": 51,
  "US/Pacific": 97,
  UTC: 87,
};

/** Slack's name for an IANA zone, if the Builder named it. */
export function slackTimeZoneName(timeZone: string): string | undefined {
  const index = ZONES[timeZone];
  return index === undefined ? undefined : NAMES[index];
}
